license = "misilelab license"

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
ignore = [
    "RUSTSEC-2021-0047",
    "RUSTSEC-2020-0071",
    "RUSTSEC-2020-0158",
    "RUSTSEC-2020-0056",
    "RUSTSEC-2022-0008",
    "RUSTSEC-2022-0048"
]
